### ISSUE TITLE
Card Values

### ISSUE THREAD

**Issue by klabe** [asmeyer2012/tarock#3]
I think we should move getCardValue from the contract classes to the Card class.  The scoring of the card-level points does not vary with contract (unless I've forgotten something?), although in certain contracts it is irrelevant.  The rules for getting from card-points to contract-points should logically go in the contract classes, though.

Do you agree?

**Comment by asmeyer2012** [comment]
This seems reasonable. I guess in my head I was equating card values with point values assigned after the completion of the round. There's no need to do these two things simultaneously.

**Comment by asmeyer2012** [comment]
I've done and pushed this now.
